apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-gradle-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-gradle
  template:
    metadata:
      labels:
        app: devops-gradle
    spec:
      containers:
        - name: devops-gradle
          image: sinemtasdemir/devops:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://database:5432/swe304
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgresql8563
