apiVersion: v1
clusters:
  - cluster:
      certificate-authority: C:\\Users\\sinem\\.minikube\\ca.crt
      extensions:
        - extension:
            last-update: Wed, 22 May 2024 12:51:09 +03
            provider: minikube.sigs.k8s.io
            version: v1.33.1
          name: cluster_info
      server: https://127.0.0.1:61860
    name: minikube
contexts:
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: Wed, 22 May 2024 12:51:09 +03
            provider: minikube.sigs.k8s.io
            version: v1.33.1
          name: context_info
      namespace: default
      user: minikube
    name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
  - name: minikube
    user:
      client-certificate: C:\\Users\\sinem\\.minikube\\profiles\\minikube\\client.crt
      client-key: C:\\Users\\sinem\\.minikube\\profiles\\minikube\\client.key
