apiVersion: v1
kind: Service
metadata:
  name: devops-gradle-service
spec:
  type: NodePort
  selector:
    app: devops-gradle
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001